fos_user:
  db_driver: orm
  firewall_name: main
  user_class: AppBundle\Entity\User
  from_email:
    address: "%env(MAILER_USER)%"
    sender_name: "%env(MAILER_USER)%"
  resetting:
    email:
      from_email:
        address:        no-reply@schicht-plan.ch
        sender_name:    Password Reset Schicht-Plan.ch