language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  include:
    - php: 7.0
    - php: 7.1

env:
  - SYMFONY_VERSION="3.3.*" DB=mysql

services:
    - mysql

before-install:
  - mysql -e 'create database akut-shift-planner_test'
  - composer self-update

install:
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer install

script:
  - composer test

notifications:
  email: jan.friedli@gmx.ch

addons:
  ssh_known_hosts: s017.cyon.net

before_deploy:
  - openssl aes-256-cbc -K $encrypted_bfabe9aee949_key -iv $encrypted_bfabe9aee949_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
  - provider: script
    skip_cleanup: true
    script: rsync -r --delete-after --links --exclude=.git/ --exclude=app/config/parameters.yml $TRAVIS_BUILD_DIR obcbtld@s017.cyon.net:/home/obcbtld/public_html/dev-schichtplan
    on:
      branch: develop
      php: 7.1
  - provider: script
    skip_cleanup: true
    script: ssh obcbtld@s017.cyon.net 'cd /home/obcbtld/public_html/dev-schichtplan/akut-shift-planner; ./post-deployment-dev.sh'
    on:
      branch: develop
      php: 7.1
  - provider: script
    skip_cleanup: true
    script: rsync -r --delete-after --links --exclude=.git/ --exclude=app/config/parameters.yml $TRAVIS_BUILD_DIR obcbtld@s017.cyon.net:/home/obcbtld/public_html/schichtplan
    on:
      tags: true
      php: 7.1
  - provider: script
    skip_cleanup: true
    script: ssh obcbtld@s017.cyon.net 'cd /home/obcbtld/public_html/schichtplan/akut-shift-planner; ./post-deployment-prod.sh'
    on:
      tags: true
      php: 7.1