imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
        name: MOCKSESSID
    profiler:
        collect: false
    default_locale: de


web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

liip_functional_test:
    cache_sqlite_db: true
    authentication:
          username: "admin"
          password: "12345678"

doctrine:
    dbal:
        driver:   pdo_sqlite
        path:     '%kernel.cache_dir%/test.db'
        charset: UTF8