# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    providers:
            fos_userbundle:
                        id: fos_user.user_provider.username_email
    encoders:
            FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
            ROLE_ADMIN:       ROLE_USER
            ROLE_SUPER_ADMIN: ROLE_ADMIN

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            logout_on_user_change: true
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                default_target_path: plan_index
                always_use_default_target_path: true
            logout:       true
            anonymous:    true

    access_control:
            - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/plan/new-by-template$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: '^/plan/[0-9A-Za-z\-]{36}$', roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/plan/new$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/person/new, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/_error, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/about, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/translations$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/plancollection/.+$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/changelog, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/, roles: ROLE_USER }
